%Langlat2012Path

/netopt/share/bin/local/bil/spm8_nutmeg_lhinkley/spm_orthviews
	/netopt/share/bin/local/bil/nutmeg4.1
	/netopt/share/bin/local/bil/nutmeg4.1/beamformers
	/netopt/share/bin/local/bil/nutmeg4.1/data_importers
	/netopt/share/bin/local/bil/nutmeg4.1/denoisers
	/netopt/share/bin/local/bil/nutmeg4.1/examples
	/netopt/share/bin/local/bil/nutmeg4.1/external
	/netopt/share/bin/local/bil/nutmeg4.1/external/ctf
	/netopt/share/bin/local/bil/nutmeg4.1/external/openmeeg
	/netopt/share/bin/local/bil/nutmeg4.1/fcm
	/netopt/share/bin/local/bil/nutmeg4.1/fcm/params
	/netopt/share/bin/local/bil/nutmeg4.1/fcm/src
	/netopt/share/bin/local/bil/nutmeg4.1/leadfield_obtainers
	/netopt/share/bin/local/bil/nutmeg4.1/nuteeg
	/netopt/share/bin/local/bil/nutmeg4.1/nuteeg/util
	/netopt/share/bin/local/bil/nutmeg4.1/nuteeg/util/Sphere_Tessellation
	/netopt/share/bin/local/bil/nutmeg4.1/openmeeglink
	/netopt/share/bin/local/bil/nutmeg4.1/templates
	/netopt/share/bin/local/bil/nutmeg4.1/tfbf
	/netopt/share/bin/local/bil/nutmeg4.1/tfbf/params
	/netopt/share/bin/local/bil/nutmeg4.1/tfbf/src
	/netopt/share/bin/local/bil/spm8_nutmeg_lhinkley/matlabbatch
	/home/dydavis/Documents/MATLAB
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/Survival
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/Survival/ex_data
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/Survival/mass_univariate
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/Survival/univariate
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/lme
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/lme/Qdec
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/lme/geodesic
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/lme/mass_univariate
	/netopt/rhel7/versions/freesurfer/freesurfer-6.0.0/matlab/lme/univariate
	/netopt/share/bin/local/bil/spm8_nutmeg_lhinkley
	/netopt/share/bin/local/bil/languagelat/advanced_voi
	/netopt/share/bin/local/bil/languagelat
	/netopt/share/bin/local/bil/verbgen_languagelat/matlab
	/netopt/share/bin/local/bil/verbgen_languagelat
	/netopt/share/bin/local/bil/m_files
	/netopt/share/matlab_versions/matlab_2012b/toolbox/local
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/general
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/ops
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/lang
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/elmat
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/randfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/elfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/specfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/matfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/datafun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/polyfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/funfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/sparfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/strfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/iofun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/timefun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/datatypes
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/verctrl
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/codetools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/helptools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/hds
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/guide
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/datamanager
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/graph2d
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/graph3d
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/graphics
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/plottools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/scribe
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/specgraph
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/uitools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/optimfun
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/demos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/comparisons
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/controllib/general
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/controllib/graphics
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/controllib/graphics/utils
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/controllib/graphics/plotoptions
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/timeseries
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/asynciolib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/testmeaslib/general
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/audiovideo
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/system
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/rptgen
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/testmeaslib/graphics
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/instrument
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/simulink
	/netopt/share/matlab_versions/matlab_2012b/toolbox/matlab/imagesci
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/coder/coder
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/optimlib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/curvefit/curvefit
	/netopt/share/matlab_versions/matlab_2012b/toolbox/curvefit/splines
	/netopt/share/matlab_versions/matlab_2012b/toolbox/curvefit/cftoolgui
	/netopt/share/matlab_versions/matlab_2012b/toolbox/curvefit/sftoolgui
	/netopt/share/matlab_versions/matlab_2012b/toolbox/curvefit/curvefitdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/database/database
	/netopt/share/matlab_versions/matlab_2012b/toolbox/database/vqb
	/netopt/share/matlab_versions/matlab_2012b/toolbox/database/dbdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/fuzzy/fuzzy
	/netopt/share/matlab_versions/matlab_2012b/toolbox/fuzzy/fuzzyutil
	/netopt/share/matlab_versions/matlab_2012b/toolbox/fuzzy/fuzdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/sam/m3i
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/dastudio
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/imageslib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/siglib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/spcuilib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/colorspaces
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/images
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/imuitools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/iptformats
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/iptutils
	/netopt/share/matlab_versions/matlab_2012b/toolbox/images/imdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/compiler
	/netopt/share/matlab_versions/matlab_2012b/toolbox/compiler/compilerdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/optim/optim
	/netopt/share/matlab_versions/matlab_2012b/toolbox/signal/signal
	/netopt/share/matlab_versions/matlab_2012b/toolbox/signal/sigtools
	/netopt/share/matlab_versions/matlab_2012b/toolbox/signal/sptoolgui
	/netopt/share/matlab_versions/matlab_2012b/toolbox/optim/optimdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/distcomp
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/user
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/mpi
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/parallel
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/parallel/util
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/lang
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/cluster
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/gpu
	/netopt/share/matlab_versions/matlab_2012b/toolbox/distcomp/pctdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/filterdesignlib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/signal/sigdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/shared/statslib
	/netopt/share/matlab_versions/matlab_2012b/toolbox/stats/stats
	/netopt/share/matlab_versions/matlab_2012b/toolbox/stats/classreg
	/netopt/share/matlab_versions/matlab_2012b/toolbox/stats/statsdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/symbolic/symbolic
	/netopt/share/matlab_versions/matlab_2012b/toolbox/symbolic/symbolicdemos
	/netopt/share/matlab_versions/matlab_2012b/toolbox/wavelet/wavelet
	/netopt/share/matlab_versions/matlab_2012b/toolbox/wavelet/wmultisig1d
	/netopt/share/matlab_versions/matlab_2012b/toolbox/wavelet/wavedemo
	/netopt/share/matlab_versions/matlab_2012b/toolbox/wavelet/compression
	/netopt/share/bin/local/bil/nutmeg