stats = struct('frqstats',true,'tsstats',false,'fsel','mean','frqband',[3:7],'frqtxt','34567', ...
    'timepts',[],'timetxt','','docomp',false,'condsel',1,'subjsel',1,'condnr',1,'subjnr',1, ...
    'whichtail','pos','corr4multfreq',true,'files',{{fullfile(pwd,'s_beamtf_verbgen2stim.mat')}});

nut_ttest_freqband(stats);


stats = struct('frqstats',true,'tsstats',false,'fsel','mean','frqband',[3:7],'frqtxt','34567', ...
    'timepts',[],'timetxt','','docomp',false,'condsel',1,'subjsel',1,'condnr',1,'subjnr',1, ...
    'whichtail','neg','corr4multfreq',true,'files',{{fullfile(pwd,'s_beamtf_verbgen2stim.mat')}});

nut_ttest_freqband(stats);