#!/bin/csh

if ( ( $# < 1 ) || ( $1 == '-help' ) ) then
   echo
   echo 'usage: verbgen1_sam dataset.ds'
   echo
   exit
endif

foreach i (`cd $VERBGENLANGUAGELAT_BASE/timeparams4sam/verbresponse; ls ??,*ms`)
   cp $VERBGENLANGUAGELAT_BASE/timeparams4sam/verbresponse/$i $1/SAM/
   qsub -p -1 -N verbgenB $VERBGENLANGUAGELAT_BASE/runsamqsubbeta $1 $i 12 30 -10 10 -8 8 1 13
end

