#!/bin/csh

if ( ( $# < 1 ) || ( $1 == '-help' ) ) then
   echo
   echo 'usage: verbgen_clean dataset.ds'
   echo
   exit
endif

cd $1/SAM/
mkdir SAMresponse
mkdir SAMstim
mv 0?,-*ms* SAMresponse
mv 1?,*ms* SAMresponse

mv 0?,+*ms* SAMstim
cd ../..
rm verbgenB.o*.1
